@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@baseUrl = {{ $processEnv REST_BASE_URL}}

###
GET {{ host }}/api/monitor/ping
###
GET {{ host }}/api/chat/init
###
GET {{ host }}/api/transactions/
